#RSiena

```{r}
#start with clean workspace 
rm(list=ls())
```


```{r}
#load dataobjects
load("./data/descriptives/RU_net_array.RData")
load("./data/descriptives/RUpub_df.RData")
load("./data/descriptives/RU_df.RData")

library(RSiena)
library(tidyverse)
```


```{r}

net1 <- net_soc_array[,,1]
net1 <- net1 + t(net1)
net1[net1==2] <- 1

net2 <- net_soc_array[,,2]
net2 <- net2 + t(net2)
net2[net2==2] <- 1

net3 <- net_soc_array[,,3]
net3 <- net3 + t(net3)
net3[net3==2] <- 1


net_soc_array <- array(data = c(net1, net2, net3), dim=c(dim(net1),3))

```


```{r}
#dependent
net <- sienaDependent(net_soc_array)

### Step 1: define data
#diversiteit egonet
#div_net <- as.numeric(soc_df$div_net=="div")
div_net <- coCovar(as.numeric(soc_df$div))
div_ego <- coCovar(as.numeric(soc_df$div.ego))
```


```{r}
#pubs: time-varying
pubsw1 <- pubsw2 <- pubsw3 <- pubsw4 <- NA
for (i in 1:length(soc_df$gs_id)) {
  pubsw1[i] <- nrow(soc_staff_cit[(soc_staff_cit$gs_id == soc_df$gs_id[i]) & soc_staff_cit$year>=2010 & soc_staff_cit$year<=2012,])
  pubsw2[i] <- nrow(soc_staff_cit[(soc_staff_cit$gs_id == soc_df$gs_id[i]) & soc_staff_cit$year>=2013 & soc_staff_cit$year<=2015,])
  pubsw3[i] <- nrow(soc_staff_cit[(soc_staff_cit$gs_id == soc_df$gs_id[i]) & soc_staff_cit$year>=2016 & soc_staff_cit$year<=2018,])
  pubsw4[i] <- nrow(soc_staff_cit[(soc_staff_cit$gs_id == soc_df$gs_id[i]) & soc_staff_cit$year>=2019 & soc_staff_cit$year<=2021,])
}

pub_df <- as.matrix(data.frame(pubsw1, pubsw2, pubsw3, pubsw4))
pubs <- varCovar(pub_df)

#year first pub
soc_staff_cit %>% group_by(gs_id) %>%
  mutate(pub_first = min(year)) %>% 
  select(c("gs_id", "pub_first")) %>%
  distinct(gs_id, pub_first, .keep_all = TRUE) -> firstpub_df

soc_df <- left_join(soc_df, firstpub_df)

#if no publication yet, set pub_first op 2023
soc_df %>% mutate(pub_first = replace_na(pub_first, 2023)) -> soc_df

pub_first <-  coCovar(soc_df$pub_first)
```


```{r}
mydata <- sienaDataCreate(net, div_ego, div_net)
```


```{r}
### Step 2: create effects structure
myeff <- getEffects(mydata)
#effectsDocumentation(myeff)
```


dit hoort dus niet hier
```{r}
mean(as.numeric(soc_df$div), na.rm = T)

mean(rowSums(net3))

mean(rowSums(net3[soc_df$div.ego==1,]))
mean(rowSums(net3[soc_df$div.ego==0,]))
```

```{r}

### Step 3: get initial description
print01Report(mydata, modelname = "./results/soc_init")
```


```{r}
### Step4: specify model
myeff <- includeEffects(myeff, degPlus) #some publish a lot, some not. (interpretation: talent/luck? )
myeff <- includeEffects(myeff, transTriads)

#myeff <- includeEffects(myeff, altX,interaction1="div_net")
#myeff <- includeEffects(myeff, egoX,interaction1="div_ego")
myeff <- includeEffects(myeff, egoPlusAltX,interaction1="div_ego")
myeff <- includeEffects(myeff, egoPlusAltX,interaction1="div_net")
```


```{r}
myeff <- includeEffects(myeff, sameX, interaction1 = "gender")
#myeff <- includeEffects(myeff, egoPlusAltX, interaction1 = "pubs") #if you have many pubs, you will probably publish more per year? 
myeff <- includeEffects(myeff, absDiffX, interaction1 = "pub_first") #senior publishes with junior
```


```{r}
### Step5 estimate
myAlgorithm <- sienaAlgorithmCreate(projname = "soc_init")
```


```{r}
(ans <- siena07(myAlgorithm, data = mydata, effects = myeff))
# (the outer parentheses lead to printing the obtained result on the screen) if necessary, estimate
# further
#(ans <- siena07(myAlgorithm, data = mydata, effects = myeff, prevAns = ans))
```



