```{r}
#start with clean workspace 
rm(list=ls())
getwd()
```

```{r}
require(tidyverse)

#data
load("./names_df2_v20221010.RData")
load("./names_df_publications_v20221010.RData")
```


```{r}
#select only RU-sociology staff
names_df %>% filter(affiliation=="Radboud University" & field=="sociology") -> soc_staff

#select the publication of these staff members you want
names_df_publications %>% filter(year>2019 & gs_id %in% soc_staff$gs_id) %>%
  select(c("author", "gs_id")) -> soc_pubs
```


```{r}
#let us clean names a bit
gs_id <- soc_pubs$gs_id
soc_pubs <- stats::aggregate(x=soc_pubs$author, by=list(gs_id), FUN=toString, na.rm=TRUE)
names(soc_pubs) <- c("gs_id", "author")

soc_staff <- left_join(soc_staff, soc_pubs)

author2 <- list()
for (i in 1: nrow(soc_staff)) {
  author2[[i]] <- unique(unlist(str_split(soc_staff$author[i], ",") ))
  author2[[i]] <- sub(author2[[i]], pattern="([A-Z]+ )", replacement=" ")
  author2[[i]] <- sub(author2[[i]], pattern="([A-Z]\\.)", replacement=" ")
  author2[[i]] <- trimws(author2[[i]])
  author2[[i]] <- unique(author2[[i]])
}
```


```{r}
soc_staff$diversiteit <- NA
author2
fix(soc_staff)

```

```{r}
div.ego <-c("1", "0", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0", "1", "0", "1", "0", "1", "0", "1", "1", "0")
```

```{r}
soc_staff_2 <- data.frame(cbind(soc_staff, div_ego = div.ego))
```


```{r}
div.egonet <-c("6.98", "0.00", "14.29", "0.00", "16.67", "0.00", "25.00", "0.00", "40.00", "60.00", "22.50", "71.43", "70.00", "0.00", "9.09", "0.00", "13.79", "28.95", "18.75", "40.00", "28.57", "4.17", "0.00", "NA", "NA", "NA", "NA", "0", "42.86", "0.00", "16.67", "0.00", "100", "78.57")
```

```{r}
soc_staff_3 <- data.frame(cbind(soc_staff_2, div_egonet = div.egonet))
```


```{r}
save(soc_staff, file = "/Users/ninab/OneDrive/Documenten/GitHub/SocialNetworkRSiena/soc_staff_1010v3.RData")
```



