```{r}
#start with clean workspace 
rm(list=ls())
getwd()
```
.
```{r}
require(tidyverse)

#data
load("./names_df2_v20220106.RData")
load("./names_df_publications_v20221006.RData")
```


```{r}
#select only RU-sociology staff
names_df %>% filter(affiliation=="Utrecht University" & field=="sociology") -> UU_staff

#select the publication of these staff members you want
names_df_publications %>% filter(year>2019 & gs_id %in% UU_staff$gs_id) %>%
  select(c("author", "gs_id")) -> UU_pubs
```


```{r}
#let us clean names a bit
gs_id <- UU_pubs$gs_id
UU_pubs <- stats::aggregate(x=UU_pubs$author, by=list(gs_id), FUN=toString, na.rm=TRUE)
names(UU_pubs) <- c("gs_id", "author")

UU_staff <- left_join(UU_staff, UU_pubs)

author2 <- list()
for (i in 1: nrow(UU_staff)) {
  author2[[i]] <- unique(unlist(str_split(UU_staff$author[i], ",") ))
  author2[[i]] <- sub(author2[[i]], pattern="([A-Z]+ )", replacement=" ")
  author2[[i]] <- sub(author2[[i]], pattern="([A-Z]\\.)", replacement=" ")
  author2[[i]] <- trimws(author2[[i]])
  author2[[i]] <- unique(author2[[i]])
}
```
```{r}
#deleting names that have gotten a wrong google scholar id
delrows <- which(UU_staff$last_name == "martens")
UU_staff <- UU_staff[-delrows, ]
```


```{r}
delrows <- which(UU_staff$last_name == "nguyen")
UU_staff <- UU_staff[-delrows, ]
```


```{r}
delrows <- which(UU_staff$last_name == "schneider")
UU_staff <- UU_staff[-delrows, ]
```


```{r}
delrows <- which(UU_staff$last_name == "janssen")
UU_staff <- UU_staff[-delrows, ]
```


```{r}
delrows <- which(UU_staff$last_name == "kroner")
UU_staff <- UU_staff[-delrows, ]
```

```{r}
delrows <- which(UU_staff$last_name == "arat")
UU_staff <- UU_staff[-delrows, ]
```


```{r}
delrows <- which(UU_staff$last_name == "fang")
UU_staff <- UU_staff[-delrows, ]
```

```{r}
delrows <- which(UU_staff$last_name == "kern")
UU_staff <- UU_staff[-delrows, ]
```


```{r}
delrows <- which(UU_staff$last_name == "van leeuwen")
UU_staff <- UU_staff[-delrows, ]
```




```{r}
UU_staff$diversiteit <- NA
author2
fix(UU_staff)

```




```{r}
div.ego <-c("1", "0", "1", "1", "0", "1", "1", "0", "1", "1", "1", "1", "1", "0", "0", "0", "1", "1", "0", "0", "1", "0", "1", "0", "1", "1", "0", "1", "1", "1", "1", "1", "1", "1")
```

```{r}
UU_staff_2 <- data.frame(cbind(UU_staff, div_ego = div.ego))
```


```{r}
div.egonet <-c("26.19", "0.00", "10.00", "31.43", "25.00", "20.83", "38.46", "89.47", "44.44", "25.00", "80.00", "37.70", "17.86", "100.00", "62.50", "42.86", "32.35", "33.33", "78.05", "28.57", "36.36", "44.00", "0.00", "57.14", "25.00", "0.00", "NA", "0.00", "28.57", "30.00", "76.92", "32.26", "0.00", "33.33")
```

```{r}
UU_staff_3 <- data.frame(cbind(UU_staff_2, div_egonet = div.egonet))
```


```{r}
save(UU_staff_3, file = "/Users/ninab/OneDrive/Documenten/GitHub/SocialNetworkRSiena/UU_staff_20221011.RData")
```

```{r}
#deleting names that have gotten a wrong google scholar id
delrows <- which(names_df_publications$gs_id == "rrh-6GEAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```


```{r}
delrows <- which(names_df_publications$gs_id == "uAc-4AwAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```


```{r}
delrows <- which(names_df_publications$gs_id == "F-VRDmoAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```


```{r}
delrows <- which(names_df_publications$gs_id == "B0uARCEAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```


```{r}
delrows <- which(names_df_publications$gs_id == "d1rRAL4AAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```

```{r}
delrows <- which(names_df_publications$gs_id == "MnDr0OkAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```


```{r}
delrows <- which(names_df_publications$gs_id == "MnDr0OkAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```

```{r}
delrows <- which(names_df_publications$gs_id == "b3aquRUAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```


```{r}
delrows <- which(names_df_publications$gs_id == "imBDaawAAAAJ")
names_df_publications <- names_df_publications[-delrows, ]
```


# network based on publications




```{r}
UU_publications <- names_df_publications[22151:30206,]
```


```{r}
library(stringr)

#empty adjacency matrix for the years 2001-2007
network2020_2021 <- matrix(NA, nrow=nrow(names_df), ncol=nrow(names_df))

#select publications of the corresponding time era
UU_pubs_sel <- UU_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>2019 & year<2022)

save(UU_pubs_sel, file = "uu_pubs_sel_2020_2021.RData")

#fill the matrix
for (ego in 1: nrow(names_df)) {
  name_ego <- names_df$last_name[ego] #which ego? 
  UU_pubs_sel <- UU_pubs_sel[str_detect(UU_pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(names_df)){
    name_alter <- names_df$last_name[alter] #which alter? 
    network2020_2021[ego,alter] <- sum(str_detect(UU_pubs_sel$author, name_alter)) > 1 #did alter publish with ego
  }
}

save(network2020_2021, file = "./UU_network2020_2021.RData")

```

```{r}

#empty adjacency matrix for the years 2008-2014
network2018_2019 <- matrix(NA, nrow=nrow(names_df), ncol=nrow(names_df))

#select publications of the corresponding time era
UU_pubs_sel <- UU_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>2017 & year<2020)

save(UU_pubs_sel, file = "./uu_pubs_sel_2018_2019.RData")

#fill the matrix
for (ego in 1: nrow(names_df)) {
  name_ego <- names_df$last_name[ego] #which ego? 
  UU_pubs_sel <- UU_pubs_sel[str_detect(UU_pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(names_df)){
    name_alter <- names_df$last_name[alter] #which alter? 
    network2018_2019[ego,alter] <- sum(str_detect(UU_pubs_sel$author, name_alter)) > 1 #did alter publish with ego
  }
}

save(network2018_2019, file = "uu_network2018_2019.RData")

```

```{r}

#empty adjacency matrix for the years 2016-2017
network2016_2017 <- matrix(NA, nrow=nrow(names_df), ncol=nrow(names_df))

#select publications of the corresponding time era
UU_pubs_sel <- UU_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>2015 & year<2018)

save(UU_pubs_sel, file = "uu_pubs_sel_2016_2017.RData")

#fill the matrix
for (ego in 1: nrow(names_df)) {
  name_ego <- names_df$last_name[ego] #which ego? 
  UU_pubs_sel <- UU_pubs_sel[str_detect(UU_pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(names_df)){
    name_alter <- names_df$last_name[alter] #which alter? 
    network2016_2017[ego,alter] <- sum(str_detect(UU_pubs_sel$author, name_alter)) > 1 #did alter publish with ego
  }
}

save(network2016_2017, file = "uu_network2016_2017.RData")
```








